# Generated by Django 5.0.6 on 2024-06-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api_app', '0002_alter_bill_customer_alter_billitem_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_shopping',
            field=models.FloatField(default=0),
        ),
    ]
