# Generated by Django 5.0.6 on 2024-06-06 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api_app', '0003_customer_total_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
